"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import Loader from "../app/loading";
import { Toaster } from 'sonner';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [isLoading, setIsLoading] = useState(true);
  
   useEffect(() => {
    setIsLoading(true);
    const timer  = setTimeout(() => { 
      setIsLoading(false);
    }, 2000);
    return () => clearTimeout(timer);
   }, [pathname]);
   
   
  // const isStudio = pathname.startsWith("/studio");
  // const isHome = pathname.startsWith("/sign-in");
  // const isAdmin = pathname.startsWith("/admin");
  // const isOrders = pathname.startsWith("/orders");
  // const isCustomers = pathname.startsWith("/customers");
  // const isStatistics = pathname.startsWith("/product-data");
  // const isReviews = pathname.startsWith("/reviews");

  // const studioAndHome = !isStudio && !isHome && !isAdmin && !isOrders && !isCustomers && !isStatistics && !isReviews


  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster richColors />
        {/* {(studioAndHome && !isLoading) && <Navbar />} */}
       {isLoading ? <Loader /> : children}
       {/* {(studioAndHome && !isLoading) && <Footer />} */}
        {/* {children} */}
      </body>
    </html>
    </ClerkProvider>
  );
}
